name: Python CI/CD (Docker)

on:
  push:
    branches:
      - docker   
  pull_request:
    branches:
      - docker   

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./GitHub_With_Docker
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: ./GitHub_With_Docker
        run: pytest -v
